// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// semantic_make_likelihood_context_prep_cpp
SEXP semantic_make_likelihood_context_prep_cpp(SEXP prepSEXP, SEXP diagnosticsSEXP);
RcppExport SEXP _AccumulatR_semantic_make_likelihood_context_prep_cpp(SEXP prepSEXPSEXP, SEXP diagnosticsSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type prepSEXP(prepSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type diagnosticsSEXP(diagnosticsSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(semantic_make_likelihood_context_prep_cpp(prepSEXP, diagnosticsSEXP));
    return rcpp_result_gen;
END_RCPP
}
// semantic_complexity_metrics_context_cpp
SEXP semantic_complexity_metrics_context_cpp(SEXP contextSEXP);
RcppExport SEXP _AccumulatR_semantic_complexity_metrics_context_cpp(SEXP contextSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type contextSEXP(contextSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(semantic_complexity_metrics_context_cpp(contextSEXP));
    return rcpp_result_gen;
END_RCPP
}
// semantic_loglik_context_cpp
SEXP semantic_loglik_context_cpp(SEXP contextSEXP, SEXP paramsSEXP, SEXP dataSEXP, SEXP okSEXP, SEXP minLLSEXP);
RcppExport SEXP _AccumulatR_semantic_loglik_context_cpp(SEXP contextSEXPSEXP, SEXP paramsSEXPSEXP, SEXP dataSEXPSEXP, SEXP okSEXPSEXP, SEXP minLLSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type contextSEXP(contextSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramsSEXP(paramsSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dataSEXP(dataSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type okSEXP(okSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type minLLSEXP(minLLSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(semantic_loglik_context_cpp(contextSEXP, paramsSEXP, dataSEXP, okSEXP, minLLSEXP));
    return rcpp_result_gen;
END_RCPP
}
// semantic_response_probabilities_context_cpp
SEXP semantic_response_probabilities_context_cpp(SEXP contextSEXP, SEXP paramsSEXP, SEXP layoutSEXP);
RcppExport SEXP _AccumulatR_semantic_response_probabilities_context_cpp(SEXP contextSEXPSEXP, SEXP paramsSEXPSEXP, SEXP layoutSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type contextSEXP(contextSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramsSEXP(paramsSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type layoutSEXP(layoutSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(semantic_response_probabilities_context_cpp(contextSEXP, paramsSEXP, layoutSEXP));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AccumulatR_semantic_make_likelihood_context_prep_cpp", (DL_FUNC) &_AccumulatR_semantic_make_likelihood_context_prep_cpp, 2},
    {"_AccumulatR_semantic_complexity_metrics_context_cpp", (DL_FUNC) &_AccumulatR_semantic_complexity_metrics_context_cpp, 1},
    {"_AccumulatR_semantic_loglik_context_cpp", (DL_FUNC) &_AccumulatR_semantic_loglik_context_cpp, 5},
    {"_AccumulatR_semantic_response_probabilities_context_cpp", (DL_FUNC) &_AccumulatR_semantic_response_probabilities_context_cpp, 3},
    {NULL, NULL, 0}
};

void accumulatr_register_ccallables(DllInfo *dll);
RcppExport void R_init_AccumulatR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    accumulatr_register_ccallables(dll);
}
