#' AccumulatR: Simulate and fit evidence-accumulation models
#'
#' \if{html}{\figure{logo.png}{options: style='float: right' alt='logo' width='120'}}
#'
#' `AccumulatR` is for researchers who work with response-time models in which
#' behavior is generated by competing or interacting accumulators. The package
#' lets you describe a model in psychologically meaningful terms, simulate
#' behavioral data, and evaluate likelihoods for fitting.
#'
#' The main workflow is:
#' 1. Start with `race_spec()`.
#' 2. Add accumulators, pools, outcomes, and timing relations.
#' 3. Call `finalize_model()` to prepare the model for simulation and fitting.
#' 4. Use `simulate()`, `prepare_data()`, `make_context()`, and `log_likelihood()`.
#'
#' The R interface is intended to stay readable and model-focused, while the
#' repeated numerical work happens in C++.
#'
#' @keywords package
"_PACKAGE"

## usethis namespace: start
#' @importFrom Rcpp sourceCpp
#' @importFrom stats setNames
#' @importFrom utils modifyList
#' @useDynLib AccumulatR, .registration = TRUE
## usethis namespace: end
NULL
