#' AccumulatR: Simulate and fit evidence-accumulation models
#'
#' \if{html}{\figure{logo.png}{options: style='float: right' alt='logo' width='120'}}
#'
#' `AccumulatR` is for researchers who work with response-time models in which
#' behavior is generated by competing or interacting accumulators. The package
#' lets you describe a model in psychologically meaningful terms, simulate
#' behavioral data, and evaluate likelihoods for fitting.
#'
#' The main workflow is:
#'
#' 1. Start with [race_spec()].
#' 2. Add accumulators, pools, outcomes, and timing relations.
#' 3. Call [finalize_model()] and supply values with [build_param_matrix()].
#' 4. Generate observations with [simulate()], or use experimental data.
#' 5. Call [prepare_data()] and [make_context()], then evaluate candidate
#'    parameters with [log_likelihood()].
#'
#' See `vignette("getting_started", package = "AccumulatR")` for a worked example.
#'
#' @keywords package
"_PACKAGE"

## usethis namespace: start
#' @importFrom stats setNames
#' @importFrom Rcpp evalCpp
#' @useDynLib AccumulatR, .registration = TRUE
## usethis namespace: end
NULL
