# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
NULL

native_context_build <- function(prepSEXP) {
    .Call(`_AccumulatR_native_context_build`, prepSEXP)
}

native_prep_serialize_cpp <- function(prepSEXP) {
    .Call(`_AccumulatR_native_prep_serialize_cpp`, prepSEXP)
}

native_context_from_proto_cpp <- function(blob) {
    .Call(`_AccumulatR_native_context_from_proto_cpp`, blob)
}

native_ctx_invalid <- function(ptr) {
    .Call(`_AccumulatR_native_ctx_invalid`, ptr)
}

cpp_loglik <- function(ctxSEXP, params_mat, data_df, ok, expand, min_ll, rel_tol, abs_tol, max_depth) {
    .Call(`_AccumulatR_cpp_loglik`, ctxSEXP, params_mat, data_df, ok, expand, min_ll, rel_tol, abs_tol, max_depth)
}

cpp_loglik_multiple <- function(ctxSEXP, params_list, data_df, ok, expand, min_ll, rel_tol, abs_tol, max_depth) {
    .Call(`_AccumulatR_cpp_loglik_multiple`, ctxSEXP, params_list, data_df, ok, expand, min_ll, rel_tol, abs_tol, max_depth)
}

native_outcome_probability_params_cpp_idx <- function(ctxSEXP, node_id, upper, component_idx, forced_complete, forced_survive, competitor_ids, rel_tol, abs_tol, max_depth, trial_rows) {
    .Call(`_AccumulatR_native_outcome_probability_params_cpp_idx`, ctxSEXP, node_id, upper, component_idx, forced_complete, forced_survive, competitor_ids, rel_tol, abs_tol, max_depth, trial_rows)
}

native_outcome_labels_cpp <- function(ctxSEXP) {
    .Call(`_AccumulatR_native_outcome_labels_cpp`, ctxSEXP)
}

#' @noRd
dist_lognormal_pdf <- function(x, m, s) {
    .Call(`_AccumulatR_dist_lognormal_pdf`, x, m, s)
}

#' @noRd
dist_lognormal_cdf <- function(x, m, s) {
    .Call(`_AccumulatR_dist_lognormal_cdf`, x, m, s)
}

#' @noRd
dist_lognormal_rng <- function(n, m, s) {
    .Call(`_AccumulatR_dist_lognormal_rng`, n, m, s)
}

#' @noRd
dist_gamma_pdf <- function(x, shape, rate) {
    .Call(`_AccumulatR_dist_gamma_pdf`, x, shape, rate)
}

#' @noRd
dist_gamma_cdf <- function(x, shape, rate) {
    .Call(`_AccumulatR_dist_gamma_cdf`, x, shape, rate)
}

#' @noRd
dist_gamma_rng <- function(n, shape, rate) {
    .Call(`_AccumulatR_dist_gamma_rng`, n, shape, rate)
}

#' @noRd
dist_exgauss_pdf <- function(x, mu, sigma, tau) {
    .Call(`_AccumulatR_dist_exgauss_pdf`, x, mu, sigma, tau)
}

#' @noRd
dist_exgauss_cdf <- function(x, mu, sigma, tau) {
    .Call(`_AccumulatR_dist_exgauss_cdf`, x, mu, sigma, tau)
}

#' @noRd
dist_exgauss_rng <- function(n, mu, sigma, tau) {
    .Call(`_AccumulatR_dist_exgauss_rng`, n, mu, sigma, tau)
}

#' @noRd
dist_lba_pdf <- function(x, v, B, A, sv) {
    .Call(`_AccumulatR_dist_lba_pdf`, x, v, B, A, sv)
}

#' @noRd
dist_lba_cdf <- function(x, v, B, A, sv) {
    .Call(`_AccumulatR_dist_lba_cdf`, x, v, B, A, sv)
}

#' @noRd
dist_lba_rng <- function(n, v, B, A, sv) {
    .Call(`_AccumulatR_dist_lba_rng`, n, v, B, A, sv)
}

#' @noRd
dist_rdm_pdf <- function(x, v, B, A, s) {
    .Call(`_AccumulatR_dist_rdm_pdf`, x, v, B, A, s)
}

#' @noRd
dist_rdm_cdf <- function(x, v, B, A, s) {
    .Call(`_AccumulatR_dist_rdm_cdf`, x, v, B, A, s)
}

#' @noRd
dist_rdm_rng <- function(n, v, B, A, s) {
    .Call(`_AccumulatR_dist_rdm_rng`, n, v, B, A, s)
}

