# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

native_context_build <- function(prepSEXP) {
    .Call(`_AccumulatR_native_context_build`, prepSEXP)
}

native_prep_serialize_cpp <- function(prepSEXP) {
    .Call(`_AccumulatR_native_prep_serialize_cpp`, prepSEXP)
}

native_context_from_proto_cpp <- function(blob) {
    .Call(`_AccumulatR_native_context_from_proto_cpp`, blob)
}

boost_integrate_cpp <- function(integrand, lower, upper, rel_tol, abs_tol, max_depth) {
    .Call(`_AccumulatR_boost_integrate_cpp`, integrand, lower, upper, rel_tol, abs_tol, max_depth)
}

native_trial_mixture_cpp <- function(ctxSEXP, node_id, t, component_ids, weights, forced_component, competitor_ids, trial_rows, guess_donors) {
    .Call(`_AccumulatR_native_trial_mixture_driver`, ctxSEXP, node_id, t, component_ids, weights, forced_component, competitor_ids, trial_rows, guess_donors)
}

cpp_loglik <- function(ctxSEXP, structure, params_mat, data_df, rel_tol, abs_tol, max_depth) {
    .Call(`_AccumulatR_cpp_loglik`, ctxSEXP, structure, params_mat, data_df, rel_tol, abs_tol, max_depth)
}

cpp_loglik_multiple <- function(ctxSEXP, structure, params_list, data_df, rel_tol, abs_tol, max_depth) {
    .Call(`_AccumulatR_cpp_loglik_multiple`, ctxSEXP, structure, params_list, data_df, rel_tol, abs_tol, max_depth)
}

native_component_plan_exported <- function(structureSEXP, trial_rowsSEXP, forced_componentSEXP) {
    .Call(`_AccumulatR_native_component_plan_exported`, structureSEXP, trial_rowsSEXP, forced_componentSEXP)
}

native_outcome_probability_params_cpp <- function(ctxSEXP, node_id, upper, component, forced_complete, forced_survive, competitor_ids, rel_tol, abs_tol, max_depth, trial_rows) {
    .Call(`_AccumulatR_native_outcome_probability_params_cpp`, ctxSEXP, node_id, upper, component, forced_complete, forced_survive, competitor_ids, rel_tol, abs_tol, max_depth, trial_rows)
}

native_outcome_labels_cpp <- function(ctxSEXP) {
    .Call(`_AccumulatR_native_outcome_labels_cpp`, ctxSEXP)
}

#' @noRd
dist_lognormal_pdf <- function(x, meanlog, sdlog) {
    .Call(`_AccumulatR_dist_lognormal_pdf`, x, meanlog, sdlog)
}

#' @noRd
dist_lognormal_cdf <- function(x, meanlog, sdlog) {
    .Call(`_AccumulatR_dist_lognormal_cdf`, x, meanlog, sdlog)
}

#' @noRd
dist_lognormal_rng <- function(n, meanlog, sdlog) {
    .Call(`_AccumulatR_dist_lognormal_rng`, n, meanlog, sdlog)
}

#' @noRd
dist_gamma_pdf <- function(x, shape, rate) {
    .Call(`_AccumulatR_dist_gamma_pdf`, x, shape, rate)
}

#' @noRd
dist_gamma_cdf <- function(x, shape, rate) {
    .Call(`_AccumulatR_dist_gamma_cdf`, x, shape, rate)
}

#' @noRd
dist_gamma_rng <- function(n, shape, rate) {
    .Call(`_AccumulatR_dist_gamma_rng`, n, shape, rate)
}

#' @noRd
dist_exgauss_pdf <- function(x, mu, sigma, tau) {
    .Call(`_AccumulatR_dist_exgauss_pdf`, x, mu, sigma, tau)
}

#' @noRd
dist_exgauss_cdf <- function(x, mu, sigma, tau) {
    .Call(`_AccumulatR_dist_exgauss_cdf`, x, mu, sigma, tau)
}

#' @noRd
dist_exgauss_rng <- function(n, mu, sigma, tau) {
    .Call(`_AccumulatR_dist_exgauss_rng`, n, mu, sigma, tau)
}

#' @noRd
pool_coeffs_cpp <- function(Svec, Fvec) {
    .Call(`_AccumulatR_pool_coeffs_cpp`, Svec, Fvec)
}

