# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

semantic_profiler_is_available_cpp <- function() {
    .Call(`_AccumulatR_semantic_profiler_is_available_cpp`)
}

semantic_profiler_start_cpp <- function(pathSEXP, frequencySEXP) {
    invisible(.Call(`_AccumulatR_semantic_profiler_start_cpp`, pathSEXP, frequencySEXP))
}

semantic_profiler_flush_cpp <- function() {
    invisible(.Call(`_AccumulatR_semantic_profiler_flush_cpp`))
}

semantic_profiler_stop_cpp <- function() {
    invisible(.Call(`_AccumulatR_semantic_profiler_stop_cpp`))
}

semantic_make_likelihood_context_prep_cpp <- function(prepSEXP) {
    .Call(`_AccumulatR_semantic_make_likelihood_context_prep_cpp`, prepSEXP)
}

semantic_prepare_trial_layout_cpp <- function(dataSEXP) {
    .Call(`_AccumulatR_semantic_prepare_trial_layout_cpp`, dataSEXP)
}

semantic_loglik_context_cpp <- function(contextSEXP, layoutSEXP, paramsSEXP, dataSEXP, minLLSEXP) {
    .Call(`_AccumulatR_semantic_loglik_context_cpp`, contextSEXP, layoutSEXP, paramsSEXP, dataSEXP, minLLSEXP)
}

